### ISSUE TITLE
Frequent use of this program

### ISSUE THREAD

**Issue by saksham1211** [aaishikasb/GitHub-Activity-Generator#4]
Hi,
I want to know what will happen if I keep on using this program again and again on a Github account?
Will Github trace this as a miscellaneous activity or what will happen exactly?

**Comment by aaishikasb** [comment]
I would not recommend you use this program, again and again. Regardless, I don't think this will be flagged by GitHub as a miscellaneous activity until someone reports the repository (which won't happen if you keep it Private). Do let me know if there is anything else I can assist you with. Also, a reminder that having a lot of commits won't help you if you don't have any decent commits. Quality > Quantity
